config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'home/howitworks'
  get 'home/map'
  get 'home/pricing'
  get 'home/about'
  get 'home/help'
  get 'home/privacy'
  get 'home/terms_of_use'
  get 'home/my_account'
  get 'home/rent'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  validates_presence_of    :identifier
  validates_uniqueness_of  :identifier

  belongs_to :current_station, class_name: :Station, foreign_key: :current_station_id, optional: true
  belongs_to :user, optional: true

end

app/models/station.rb
class Station < ApplicationRecord
  validates_presence_of    :identifier,
                           :name,
                           :address
  validates_uniqueness_of  :identifier
  
  has_many :docked_bikes, class_name: :Bike, foreign_key: :current_station_id
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    def bikes
        @bikes = Bike.all.order(identifier: :asc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
    def index
    end

    def howitworks
    end
    
    def map
    end

    def pricing
    end

    def about
    end
    
    def help
    end

    def login
    end

    def privacy
    end
    
    def terms_of_use
    end

    def rent
    end
  
  end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  
  def index
    @stations = Station.all.order(identifier: :asc)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/bikes/_row.html.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox vertical stretch">
  Bike ID: <%= bikes.identifier %> ... Bike Location: <%= bikes.current_station.name %>
</div>

app/views/bikes/bikes.html.erb
<div class="page-section flexbox vertical stretch">
  <div class="section-inner flexbox vertical stretch">
    <div class="section-title">
      This is ValetBike :D!
    </div>
    <a href="/">Station Spots</a>
    <div class="flexbox vertical stretch">
      <% if @bikes.present? %>
        <%= render(partial: "bikes/row", collection: @bikes, as: :bikes) %>
      <% else %>
      <div class="empty">
        No bikes found.
      </div>
      <% end %>
    </div>
	</div>
</div>

app/views/home/about.html.erb
<% content_for :title, "About | ValetBike" %>
<p> This is the About Us page. </p>

app/views/home/help.html.erb
<% content_for :title, "Help | ValetBike" %>
<p> This is the Help page. </p>

app/views/home/howitworks.html.erb
<% content_for :title, "How It Works | ValetBike" %>
<p> This is the How It Works page. </p>

app/views/home/index.html.erb
<% content_for :title, "ValetBike" %>

<div class="page-section flexbox vertical stretch">
  <div class="hero flexbox vertical stretch">  
    <h1>Welcome to ValetBike!</h1>
    <h2>Subtitle goes here</h2>
	</div>
  <div role="button" type="button" class="button">
    <%= link_to 'Rent a Bike!', home_map_path %>
  </div><br>
  <div class="section-inner flexbox vertical stretch">
    <h1>What we do:</h1>
    <p>Something about our mission.</p>
  </div>

  
</div>

app/views/home/login.html.erb
<% content_for :title, "Login | ValetBike" %>
<p> This is the Login page. </p>

app/views/home/map.html.erb
<% content_for :title, "Map | ValetBike" %>

<div class="page-section flexbox vertical stretch">
    <div class="section-inner flexbox vertical stretch">

        <h1>ValetBike Map Page</h1>
        <!-- Title will be removed later? -->

        <div class="map__container flexbox horizontal stretch" id="map">
            <!-- Made map__container class in case it needs adjustments -->
            <%# fix line 14 %>
            <%# <script type="text/javascript" src="../assets/javascripts/map.js"></script> %>

            <!-- img src="../assets/placeholder-map-pin.png" -->

            <script> <!--  script tag from: https://github.com/CJParkNW/valetbike/commit/f21be0e9c3e0b2a8e1dedffefbc207081902027b-->
            var map = L.map('map').setView([42.32, -72.65], 13);
          
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
              attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          }).addTo(map);
          
            L.marker([42.32, -72.65]).addTo(map)
              .bindPopup('Welcome to Northampton! We have Valetbike here!')
              .openPopup();
            </script>
                
            </div>

    </div>

    <div class="section-inner flexbox vertical stretch">
        <div class ="location-info__container flexbox vertical stretch">
            <!-- Made location-info__container class in case it needs adjustments (scroll-bar, visibility, etc.) -->
            <h2> Location Info </h2>
            <!-- Rent page should auto-populate with location chosen -->
            <ol type="1" class="location-info__text">
                <li>
                    Station 1:
                    <ul>
                        Bikes available: #
                    </ul>
                    <ul>
                        <div role="button" type="button" class="button">
                            <%= link_to 'Rent', home_rent_path %>
                        </div>
                    </ul>
                </li>
                <li>Station 2
                    <ul>
                    Bikes available: #
                    </ul>
                    <ul>
                        <div role="button" type="button" class="button">
                            <%= link_to 'Rent', home_rent_path %>
                        </div>
                    </ul>
                </li>
            </ol>
            <!-- Made location-info__text class in case it needs adjustments -->
        </div>
    </div>

</div>

app/views/home/my_account.html.erb
<% content_for :title, "Help | ValetBike" %>
<p> This is the My Account page. </p>

app/views/home/pricing.html.erb
<% content_for :title, "Pricing | ValetBike" %>
<p> This is the Pricing page. </p>

app/views/home/privacy.html.erb
<% content_for :title, "Privacy Policy | ValetBike" %>
<p> This is a Privacy Policy. </p>

app/views/home/register.html.erb
<p> Register </p>

<form> 

<label>Name</label>
<input>
<label>Email</label>
<input>
<button>Sign Up</button>
</form>

app/views/home/rent.html.erb
<% content_for :title, "Rent | ValetBike" %>
<p>This is the Rent page.</p>

app/views/home/terms_of_use.html.erb
<% content_for :title, "Terms of Use | ValetBike" %>
<p> This is a Terms of Use. </p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,500,700" rel="stylesheet" type="text/css">
    <link href="/favicon.ico" rel="icon" type="image/x-icon">

     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   
    <title><%= yield(:title) %></title>
  </head>
  <body>
    <div id="site-container" class="flexbox vertical stretch flex-1">
      <div class="flexbox vertical center">

        <nav role="navigation" id="mainNav" class="navbar container" aria-label="navigation bar">
          <%= link_to 'Home', root_path, class: "nav-link" %>
          <%= link_to 'How It Works', home_howitworks_path, class: "nav-link" %>
          <%= link_to 'Map', home_map_path, class: "nav-link" %>
          <%= link_to 'Pricing', home_pricing_path, class: "nav-link" %>
          <%= link_to 'About Us', home_about_path, class: "nav-link" %>
          <%= link_to 'Help', home_help_path, class: "nav-link" %>
          <% if user_signed_in? %>
            <%= link_to 'My Account', home_my_account_path, class: "nav-link" %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%# <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            <%= link_to 'Log In/Sign Up', new_user_session_path, class: "nav-link" %>
          <% end %>

        </nav>

        <%= yield %>
        <footer>
          <p> Email us at: </p> <br />
          <p> Call us at: </p> <br />
          <%= link_to 'Privacy Policy', home_privacy_path %>
          <%= link_to 'Terms of Use', home_terms_of_use_path %> <br />
          <em> Copyright Information </em>
        </footer>
      </div>
    </div>
  </body>
   <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
</html>

app/views/stations/_row.html.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox vertical stretch">
  <%= station.identifier %>: <%= station.name %> (<%= station.address %>)
</div>

app/views/stations/index.html.erb
<div class="page-section flexbox vertical stretch">
  <div class="section-inner flexbox vertical stretch">
    <div class="section-title">
      Welcome to ValetBike!
    </div>  
    <div class="flexbox vertical stretch">
      <% if @stations.present? %>
        <%= render(partial: "stations/row", collection: @stations, as: :station) %>
      <% else %>
      <div class="empty">
        No stations found.
      </div>
      <% end %>
    </div>
	</div>
</div>